---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: remove image
      command: docker rmi elshwaihi/iattend-jen
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t elshwaihi/iattend-jen .

    - name: Push Image to dockerhub
      command: docker push elshwaihi/iattend-jen
      ignore_errors: yes
