---
- name: "Build with ansible"
  hosts: my_ec2
  ansible_ssh_private_key_file: ./terraform/mykey.pem
  remote_user: ubuntu  # Replace with the correct username for your EC2 instance 
  become: yes  # If you need to run tasks with sudo
  tasks:
    - name: remove image
      command: docker rmi muhammadelmansi/depi_final
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t muhammadelmansi/depi_final .

    - name: Push Image to dockerhub
      command: docker push muhammadelmansi/depi_final
      ignore_errors: yes
      
    - name: stop and remove containers
      command: docker-compose down
      ignore_errors: yes

    - name: build docker-compose
      command: docker-compose up -d 
