version: '3.8'

services:
  db:
    container_name: mysqldb
    image: mysql:8.0
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: django_user
      MYSQL_PASSWORD: djangopassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend

  web:
    container_name: django_cont
    image: elshwaihi/iattend-jen
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db:
          condition: healthcheck
    environment:
      - DEBUG=1
      - DB_NAME=django_db
      - DB_USER=django_user
      - DB_PASSWORD=djangopassword
      - DB_HOST=db
      - DB_PORT=3306
    networks:
      - backend
      - frontend

  proxy:
    container_name: nginx_proxy
    image: nginx
    volumes:
    
    networks:
      - frontend
    depends_on:
      - web

volumes:
  db_data:
networks:
  backend:
  frontend:
