version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: djangopassword
    ports:
      - "5050:3306"

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=django_db
      - DB_USER=django_user
      - DB_PASSWORD=djangopassword
      - DB_HOST=db
      - DB_PORT=3306

volumes:
  db_data:
