---
- name: "Run Docker-Compose using ansible playbook"
  hosts: localhost
  tasks:
  - name: stop and remove containers
    command: docker-compose down
    ignore_errors: yes

  - name: build docker-compose
    command: docker-compose up -d 
