---
- name: "Run Docker-Compose using ansible playbook"
  hosts: localhost
  tasks:
  - name: stop and remove containers
    command: docker-compose down
    ignore_errors: yes

  # Make sure to change the image name with your personal dockerhub account and reposiroty 
  - name: remove image built with dockercompose
    command: docker rmi elshwaihi/iattend-jen
    ignore_errors: yes

  - name: build docker-compose
    command: docker-compose up -d 
