apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqldb
  namespace: proj
spec:
  selector:
    matchLabels:
      app: mysqldb
  serviceName: "mysqldb"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "django_db"
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_USER
              value: "django_user"
            - name: MYSQL_PASSWORD
              value: "djangopassword"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
